import { StyleSheet, Dimensions, Platform } from 'react-native';
import { APP_CONSTANTS } from '@/config/constants';

const { width, height } = Dimensions.get('window');
const isWeb = Platform.OS === 'web';

export const authStyles = StyleSheet.create({
  // Container styles
  container: {
    flex: 1,
    backgroundColor: 'white',
    minHeight: isWeb ? height : '100%',
  },
  gradient: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: isWeb ? 40 : 20,
    paddingVertical: isWeb ? 60 : 16,
    position: 'relative',
    minHeight: isWeb ? height : '100%',
  },
  contentContainer: {
    alignItems: 'center',
    width: '100%',
    maxWidth: isWeb ? 600 : '100%',
    minHeight: isWeb ? height * 0.8 : 'auto',
    justifyContent: 'space-between',
  },
  formContainer: {
    alignItems: 'center',
    width: '100%',
    maxWidth: isWeb ? 500 : 350,
    minHeight: isWeb ? height * 0.7 : 'auto',
    justifyContent: 'center',
  },

  // Logo styles
  logoContainer: {
    alignItems: 'center',
    marginBottom: isWeb ? 48 : 28,
    marginTop: isWeb ? 40 : 0,
  },
  logoBackground: {
    backgroundColor: 'white',
    borderRadius: isWeb ? 24 : 18,
    paddingHorizontal: isWeb ? 32 : 20,
    paddingVertical: isWeb ? 20 : 14,
    shadowColor: APP_CONSTANTS.COLORS.PRIMARY,
    shadowOffset: { width: 0, height: isWeb ? 12 : 6 },
    shadowOpacity: 0.15,
    shadowRadius: isWeb ? 20 : 12,
    elevation: 6,
    marginBottom: isWeb ? 20 : 12,
  },
  logoText: {
    fontSize: isWeb ? 56 : 42,
    fontWeight: '800',
    color: APP_CONSTANTS.COLORS.PRIMARY,
    fontFamily: 'SF Pro Display, Inter, sans-serif',
    letterSpacing: -1,
  },
  tagline: {
    fontSize: isWeb ? 18 : 14,
    color: APP_CONSTANTS.COLORS.TEXT_SECONDARY,
    fontFamily: 'Inter, sans-serif',
    fontWeight: '600',
  },

  // Text styles
  title: {
    fontSize: isWeb ? 32 : 26,
    fontWeight: '800',
    color: APP_CONSTANTS.COLORS.TEXT_PRIMARY,
    textAlign: 'center',
    marginBottom: isWeb ? 16 : 10,
    fontFamily: 'Inter, sans-serif',
  },
  subtitle: {
    fontSize: isWeb ? 18 : 15,
    color: APP_CONSTANTS.COLORS.TEXT_SECONDARY,
    textAlign: 'center',
    marginBottom: isWeb ? 32 : 20,
    fontFamily: 'Inter, sans-serif',
    lineHeight: isWeb ? 26 : 20,
    fontWeight: '500',
  },
  description: {
    fontSize: isWeb ? 22 : 17,
    color: APP_CONSTANTS.COLORS.TEXT_PRIMARY,
    textAlign: 'center',
    lineHeight: isWeb ? 32 : 24,
    fontFamily: 'Inter, sans-serif',
    fontWeight: '500',
  },
  descriptionContainer: {
    marginBottom: isWeb ? 64 : 36,
    paddingHorizontal: isWeb ? 40 : 16,
    flex: isWeb ? 1 : 0,
    justifyContent: 'center',
  },

  // Button styles
  buttonContainer: {
    width: '100%',
    marginBottom: isWeb ? 60 : 40,
  },
  button: {
    backgroundColor: 'white',
    borderRadius: isWeb ? 20 : 12,
    marginBottom: isWeb ? 20 : 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: isWeb ? 6 : 2 },
    shadowOpacity: 0.08,
    shadowRadius: isWeb ? 16 : 6,
    elevation: 2,
    borderWidth: 1,
    borderColor: APP_CONSTANTS.COLORS.BORDER_LIGHT,
    minHeight: isWeb ? 'auto' : 52,
    width: isWeb ? 'auto' : '100%',
    alignSelf: isWeb ? 'auto' : 'stretch',
  },
  buttonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: isWeb ? 24 : 12,
    paddingHorizontal: isWeb ? 32 : 32,
    width: '100%',
  },
  buttonIconContainer: {
    width: isWeb ? 56 : 32,
    height: isWeb ? 56 : 32,
    borderRadius: isWeb ? 16 : 8,
    backgroundColor: `${APP_CONSTANTS.COLORS.PRIMARY}10`,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: isWeb ? 20 : 16,
  },
  buttonTextContainer: {
    flex: 1,
    marginRight: isWeb ? 0 : 8,
    justifyContent: 'center',
  },
  buttonTitle: {
    fontSize: isWeb ? 20 : 14,
    fontWeight: '700',
    color: APP_CONSTANTS.COLORS.TEXT_PRIMARY,
    marginBottom: isWeb ? 6 : 1,
    fontFamily: 'Inter, sans-serif',
    flexShrink: 1,
    textAlign: 'left',
  },
  buttonSubtitle: {
    fontSize: isWeb ? 16 : 11,
    color: APP_CONSTANTS.COLORS.TEXT_SECONDARY,
    fontFamily: 'Inter, sans-serif',
    fontWeight: '400',
    flexShrink: 1,
    textAlign: 'left',
  },
  primaryButton: {
    backgroundColor: APP_CONSTANTS.COLORS.PRIMARY,
    borderRadius: isWeb ? 20 : 16,
    paddingVertical: isWeb ? 20 : 16,
    paddingHorizontal: isWeb ? 32 : 24,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: APP_CONSTANTS.COLORS.PRIMARY,
    shadowOffset: { width: 0, height: isWeb ? 8 : 4 },
    shadowOpacity: 0.2,
    shadowRadius: isWeb ? 16 : 8,
    elevation: 6,
    marginBottom: isWeb ? 20 : 16,
  },
  primaryButtonText: {
    fontSize: isWeb ? 18 : 16,
    fontWeight: '600',
    color: 'white',
    fontFamily: 'Inter, sans-serif',
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    borderRadius: isWeb ? 20 : 16,
    paddingVertical: isWeb ? 20 : 16,
    paddingHorizontal: isWeb ? 32 : 24,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: APP_CONSTANTS.COLORS.PRIMARY,
    marginBottom: isWeb ? 20 : 16,
  },
  secondaryButtonText: {
    fontSize: isWeb ? 18 : 16,
    fontWeight: '600',
    color: APP_CONSTANTS.COLORS.PRIMARY,
    fontFamily: 'Inter, sans-serif',
  },

  // Form styles
  form: {
    width: '100%',
    marginBottom: isWeb ? 40 : 32,
  },
  inputContainer: {
    marginBottom: isWeb ? 24 : 20,
  },
  input: {
    backgroundColor: 'white',
    borderRadius: isWeb ? 16 : 12,
    paddingVertical: isWeb ? 18 : 16,
    paddingHorizontal: isWeb ? 20 : 16,
    fontSize: isWeb ? 16 : 14,
    borderWidth: 1,
    borderColor: APP_CONSTANTS.COLORS.BORDER,
    fontFamily: 'Inter, sans-serif',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  inputFocused: {
    borderColor: APP_CONSTANTS.COLORS.PRIMARY,
    shadowColor: APP_CONSTANTS.COLORS.PRIMARY,
    shadowOpacity: 0.1,
  },
  inputLabel: {
    fontSize: isWeb ? 16 : 14,
    fontWeight: '500',
    color: APP_CONSTANTS.COLORS.TEXT_PRIMARY,
    marginBottom: isWeb ? 8 : 6,
    fontFamily: 'Inter, sans-serif',
  },
  inputError: {
    borderColor: APP_CONSTANTS.COLORS.ERROR,
  },
  errorText: {
    fontSize: isWeb ? 14 : 12,
    color: APP_CONSTANTS.COLORS.ERROR,
    marginTop: isWeb ? 6 : 4,
    fontFamily: 'Inter, sans-serif',
  },

  // Link styles
  linkContainer: {
    alignItems: 'center',
    marginTop: isWeb ? 24 : 20,
  },
  link: {
    fontSize: isWeb ? 16 : 14,
    color: APP_CONSTANTS.COLORS.PRIMARY,
    textDecorationLine: 'underline',
    fontFamily: 'Inter, sans-serif',
    fontWeight: '500',
  },
  linkText: {
    fontSize: isWeb ? 16 : 14,
    color: APP_CONSTANTS.COLORS.TEXT_SECONDARY,
    fontFamily: 'Inter, sans-serif',
  },

  // Footer styles
  footer: {
    alignItems: 'center',
    paddingHorizontal: isWeb ? 40 : 16,
    marginTop: isWeb ? 'auto' : 0,
  },
  footerText: {
    fontSize: isWeb ? 16 : 13,
    color: APP_CONSTANTS.COLORS.TEXT_TERTIARY,
    textAlign: 'center',
    fontFamily: 'Inter, sans-serif',
    fontWeight: '500',
  },

  // Decorative elements
  decorativeCircle1: {
    position: 'absolute',
    top: isWeb ? height * 0.05 : height * 0.1,
    right: isWeb ? width * 0.15 : width * 0.1,
    width: isWeb ? 160 : 120,
    height: isWeb ? 160 : 120,
    borderRadius: isWeb ? 80 : 60,
    backgroundColor: `${APP_CONSTANTS.COLORS.PRIMARY}10`,
  },
  decorativeCircle2: {
    position: 'absolute',
    bottom: isWeb ? height * 0.15 : height * 0.2,
    left: isWeb ? width * 0.08 : width * 0.05,
    width: isWeb ? 120 : 80,
    height: isWeb ? 120 : 80,
    borderRadius: isWeb ? 60 : 40,
    backgroundColor: `${APP_CONSTANTS.COLORS.PRIMARY}08`,
  },
  decorativeCircle3: {
    position: 'absolute',
    top: isWeb ? height * 0.25 : height * 0.3,
    left: isWeb ? width * 0.2 : width * 0.15,
    width: isWeb ? 100 : 60,
    height: isWeb ? 100 : 60,
    borderRadius: isWeb ? 50 : 30,
    backgroundColor: `${APP_CONSTANTS.COLORS.PRIMARY}06`,
  },
  decorativeCircle4: {
    position: 'absolute',
    top: isWeb ? height * 0.4 : 0,
    right: isWeb ? width * 0.05 : 0,
    width: isWeb ? 80 : 0,
    height: isWeb ? 80 : 0,
    borderRadius: isWeb ? 40 : 0,
    backgroundColor: `${APP_CONSTANTS.COLORS.PRIMARY}05`,
  },
  decorativeCircle5: {
    position: 'absolute',
    bottom: isWeb ? height * 0.35 : 0,
    right: isWeb ? width * 0.25 : 0,
    width: isWeb ? 140 : 0,
    height: isWeb ? 140 : 0,
    borderRadius: isWeb ? 70 : 0,
    backgroundColor: `${APP_CONSTANTS.COLORS.PRIMARY}07`,
  },

  // Divider styles
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: isWeb ? 24 : 20,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: APP_CONSTANTS.COLORS.BORDER,
  },
  dividerText: {
    fontSize: isWeb ? 14 : 12,
    color: APP_CONSTANTS.COLORS.TEXT_SECONDARY,
    marginHorizontal: isWeb ? 16 : 12,
    fontFamily: 'Inter, sans-serif',
  },

  // Loading and disabled states
  disabledButton: {
    opacity: 0.6,
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    fontSize: isWeb ? 16 : 14,
    color: APP_CONSTANTS.COLORS.TEXT_SECONDARY,
    marginLeft: isWeb ? 12 : 8,
    fontFamily: 'Inter, sans-serif',
  },

  // Signup Flow specific styles
  signupContainer: {
    flex: 1,
    backgroundColor: 'white',
    minHeight: isWeb ? height : '100%',
  },
  signupGradient: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: isWeb ? 40 : 24,
    paddingVertical: isWeb ? 20 : 10,
    position: 'relative',
    minHeight: isWeb ? height : '100%',
  },
  signupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: isWeb ? 40 : 16,
    paddingTop: isWeb ? 20 : (Platform.OS === 'android' ? 16 : 10),
    paddingBottom: isWeb ? 16 : 8,
    backgroundColor: 'transparent',
    width: '100%',
    maxWidth: isWeb ? 800 : '100%',
  },
  signupBackButton: {
    padding: isWeb ? 12 : 8,
    borderRadius: isWeb ? 12 : 8,
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: isWeb ? 4 : 2 },
    shadowOpacity: 0.1,
    shadowRadius: isWeb ? 8 : 4,
    elevation: 2,
  },
  signupStepIndicatorContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    gap: isWeb ? 12 : 8,
  },
  signupStepIndicator: {
    width: isWeb ? 12 : 10,
    height: isWeb ? 12 : 10,
    borderRadius: isWeb ? 6 : 5,
    backgroundColor: APP_CONSTANTS.COLORS.BORDER_LIGHT,
    marginHorizontal: isWeb ? 6 : 4,
  },
  signupStepIndicatorActive: {
    backgroundColor: APP_CONSTANTS.COLORS.PRIMARY_LIGHT,
    width: isWeb ? 14 : 12,
    height: isWeb ? 14 : 12,
    borderRadius: isWeb ? 7 : 6,
  },
  signupStepIndicatorCurrent: {
    backgroundColor: APP_CONSTANTS.COLORS.PRIMARY,
    width: isWeb ? 16 : 14,
    height: isWeb ? 16 : 14,
    borderRadius: isWeb ? 8 : 7,
    shadowColor: APP_CONSTANTS.COLORS.PRIMARY,
    shadowOffset: { width: 0, height: isWeb ? 4 : 2 },
    shadowOpacity: 0.3,
    shadowRadius: isWeb ? 8 : 4,
    elevation: 4,
  },
  signupScrollContent: {
    flexGrow: 1,
    paddingHorizontal: isWeb ? 40 : 24,
    paddingBottom: isWeb ? 60 : 40,
    width: '100%',
    maxWidth: isWeb ? 800 : '100%',
  },
  signupStepContainer: {
    flex: 1,
    alignItems: 'center',
    marginTop: isWeb ? 20 : 15,
    width: '100%',
    minHeight: isWeb ? height * 0.7 : '100%',
  },
  signupAnimatedContainer: {
    width: '100%',
  },
  signupStepContent: {
    width: '100%',
    paddingBottom: isWeb ? 30 : 20,
    paddingHorizontal: isWeb ? 0 : 16,
    alignItems: 'stretch',
  },
  signupStepTitle: {
    fontSize: isWeb ? 36 : 28,
    fontWeight: 'bold',
    color: APP_CONSTANTS.COLORS.TEXT_PRIMARY,
    marginBottom: isWeb ? 16 : 12,
    textAlign: 'center',
    fontFamily: 'Inter, sans-serif',
    width: '100%',
  },
  signupStepDescription: {
    fontSize: isWeb ? 18 : 16,
    color: APP_CONSTANTS.COLORS.TEXT_SECONDARY,
    marginBottom: isWeb ? 32 : 24,
    textAlign: 'center',
    lineHeight: isWeb ? 26 : 22,
    fontFamily: 'Inter, sans-serif',
    paddingHorizontal: isWeb ? 0 : 8,
    width: '100%',
  },
  signupStepSubtitle: {
    fontSize: isWeb ? 16 : 14,
    color: APP_CONSTANTS.COLORS.TEXT_SECONDARY,
    marginBottom: isWeb ? 24 : 20,
    textAlign: 'center',
    lineHeight: isWeb ? 22 : 20,
    fontFamily: 'Inter, sans-serif',
  },
  signupInputContainer: {
    marginBottom: isWeb ? 24 : 20,
    width: '100%',
  },
  signupInputLabel: {
    fontSize: isWeb ? 16 : 14,
    fontWeight: '600',
    color: APP_CONSTANTS.COLORS.TEXT_PRIMARY,
    marginBottom: isWeb ? 8 : 6,
    fontFamily: 'Inter, sans-serif',
  },
  signupInputLabelSmall: {
    fontSize: isWeb ? 14 : 13,
    fontWeight: '500',
    color: APP_CONSTANTS.COLORS.TEXT_SECONDARY,
    marginBottom: isWeb ? 6 : 5,
    fontFamily: 'Inter, sans-serif',
  },
  signupInput: {
    backgroundColor: 'white',
    paddingHorizontal: isWeb ? 20 : 16,
    paddingVertical: isWeb ? 18 : 14,
    borderRadius: isWeb ? 16 : 12,
    fontSize: isWeb ? 16 : 14,
    borderWidth: 1,
    borderColor: APP_CONSTANTS.COLORS.BORDER,
    color: APP_CONSTANTS.COLORS.TEXT_PRIMARY,
    width: '100%',
    fontFamily: 'Inter, sans-serif',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  signupInputFocused: {
    borderColor: APP_CONSTANTS.COLORS.PRIMARY,
    shadowColor: APP_CONSTANTS.COLORS.PRIMARY,
    shadowOpacity: 0.1,
  },
  signupInputError: {
    borderColor: APP_CONSTANTS.COLORS.ERROR,
  },
  signupInputValid: {
    borderColor: APP_CONSTANTS.COLORS.SUCCESS || '#28a745',
  },
  signupInputBio: {
    backgroundColor: 'white',
    paddingHorizontal: isWeb ? 20 : 16,
    paddingVertical: isWeb ? 16 : 12,
    borderRadius: isWeb ? 16 : 12,
    fontSize: isWeb ? 15 : 14,
    borderWidth: 1,
    borderColor: APP_CONSTANTS.COLORS.BORDER,
    color: APP_CONSTANTS.COLORS.TEXT_PRIMARY,
    width: '100%',
    minHeight: isWeb ? 120 : 100,
    textAlignVertical: 'top',
    fontFamily: 'Inter, sans-serif',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  signupRowContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: isWeb ? 0 : 4,
  },
  signupTermsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: isWeb ? 16 : 12,
    marginTop: isWeb ? 12 : 8,
    width: '100%',
    paddingHorizontal: isWeb ? 0 : 4,
  },
  signupCheckbox: {
    width: isWeb ? 24 : 20,
    height: isWeb ? 24 : 20,
    borderWidth: 1.5,
    borderColor: APP_CONSTANTS.COLORS.BORDER_DARK,
    borderRadius: isWeb ? 6 : 4,
    marginRight: isWeb ? 12 : 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  signupCheckboxChecked: {
    backgroundColor: APP_CONSTANTS.COLORS.PRIMARY,
    borderColor: APP_CONSTANTS.COLORS.PRIMARY,
  },
  signupTermsText: {
    fontSize: isWeb ? 14 : 13,
    color: APP_CONSTANTS.COLORS.TEXT_SECONDARY,
    lineHeight: isWeb ? 20 : 18,
    flex: 1,
    fontFamily: 'Inter, sans-serif',
  },
  signupTermsLink: {
    color: APP_CONSTANTS.COLORS.PRIMARY,
    fontWeight: '600',
    textDecorationLine: 'underline',
    fontFamily: 'Inter, sans-serif',
  },
  signupRequiredText: {
    fontSize: isWeb ? 13 : 12,
    color: APP_CONSTANTS.COLORS.TEXT_SECONDARY,
    marginTop: isWeb ? 6 : 4,
    marginBottom: isWeb ? 20 : 16,
    textAlign: isWeb ? 'right' : 'center',
    width: '100%',
    fontFamily: 'Inter, sans-serif',
  },
  signupProfilePicContainer: {
    alignItems: 'center',
    marginVertical: isWeb ? 20 : 15,
  },
  signupProfilePicPreview: {
    width: isWeb ? 120 : 100,
    height: isWeb ? 150 : 125,
    borderRadius: isWeb ? 16 : 12,
    marginBottom: isWeb ? 16 : 12,
    backgroundColor: APP_CONSTANTS.COLORS.BORDER_LIGHT,
    borderWidth: 2,
    borderColor: APP_CONSTANTS.COLORS.PRIMARY_LIGHT,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: isWeb ? 8 : 4 },
    shadowOpacity: 0.1,
    shadowRadius: isWeb ? 16 : 8,
    elevation: 4,
  },
  signupProfilePicPlaceholder: {
    width: isWeb ? 120 : 100,
    height: isWeb ? 150 : 125,
    borderRadius: isWeb ? 16 : 12,
    backgroundColor: `${APP_CONSTANTS.COLORS.BORDER_LIGHT}80`,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: isWeb ? 16 : 12,
    borderWidth: 1,
    borderColor: APP_CONSTANTS.COLORS.BORDER,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: isWeb ? 4 : 2 },
    shadowOpacity: 0.05,
    shadowRadius: isWeb ? 8 : 4,
    elevation: 2,
  },
  signupUploadButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: APP_CONSTANTS.COLORS.PRIMARY,
    paddingHorizontal: isWeb ? 24 : 20,
    paddingVertical: isWeb ? 14 : 10,
    borderRadius: isWeb ? 20 : 16,
    elevation: 3,
    shadowColor: APP_CONSTANTS.COLORS.PRIMARY,
    shadowOffset: { width: 0, height: isWeb ? 6 : 4 },
    shadowOpacity: 0.2,
    shadowRadius: isWeb ? 12 : 8,
  },
  signupUploadButtonText: {
    color: 'white',
    fontWeight: '600',
    fontSize: isWeb ? 15 : 14,
    fontFamily: 'Inter, sans-serif',
  },
  signupBioHeader: {
    marginTop: isWeb ? 20 : 15,
    marginBottom: isWeb ? 12 : 10,
    fontSize: isWeb ? 18 : 16,
    fontWeight: '600',
    textAlign: 'left',
    width: '100%',
    fontFamily: 'Inter, sans-serif',
  },
  signupContinueButton: {
    backgroundColor: APP_CONSTANTS.COLORS.PRIMARY,
    paddingVertical: isWeb ? 18 : 16,
    borderRadius: isWeb ? 16 : 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: isWeb ? 24 : 20,
    marginBottom: isWeb ? 20 : 16,
    width: '100%',
    minHeight: isWeb ? 56 : 50,
    elevation: 4,
    shadowColor: APP_CONSTANTS.COLORS.PRIMARY,
    shadowOffset: { width: 0, height: isWeb ? 8 : 4 },
    shadowOpacity: 0.2,
    shadowRadius: isWeb ? 16 : 8,
    paddingHorizontal: isWeb ? 0 : 16,
    alignSelf: 'center',
  },
  signupContinueButtonDisabled: {
    backgroundColor: APP_CONSTANTS.COLORS.DISABLED,
    elevation: 0,
    shadowOpacity: 0,
  },
  signupContinueButtonText: {
    color: 'white',
    fontWeight: '600',
    fontSize: isWeb ? 18 : 16,
    fontFamily: 'Inter, sans-serif',
  },
  signupButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: isWeb ? 24 : 20,
    gap: isWeb ? 16 : 12,
  },
  signupPrimaryButton: {
    flex: 1,
    backgroundColor: APP_CONSTANTS.COLORS.PRIMARY,
    paddingVertical: isWeb ? 18 : 16,
    borderRadius: isWeb ? 16 : 12,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: APP_CONSTANTS.COLORS.PRIMARY,
    shadowOffset: { width: 0, height: isWeb ? 6 : 4 },
    shadowOpacity: 0.2,
    shadowRadius: isWeb ? 12 : 8,
  },
  signupPrimaryButtonDisabled: {
    backgroundColor: APP_CONSTANTS.COLORS.DISABLED,
    elevation: 0,
    shadowOpacity: 0,
  },
  signupPrimaryButtonText: {
    color: 'white',
    fontWeight: '600',
    fontSize: isWeb ? 16 : 15,
    fontFamily: 'Inter, sans-serif',
  },
  signupSecondaryButton: {
    flex: 1,
    backgroundColor: 'white',
    paddingVertical: isWeb ? 18 : 16,
    borderRadius: isWeb ? 16 : 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: APP_CONSTANTS.COLORS.BORDER,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: isWeb ? 4 : 2 },
    shadowOpacity: 0.1,
    shadowRadius: isWeb ? 8 : 4,
    elevation: 2,
  },
  signupSecondaryButtonText: {
    color: APP_CONSTANTS.COLORS.TEXT_PRIMARY,
    fontWeight: '600',
    fontSize: isWeb ? 16 : 15,
    fontFamily: 'Inter, sans-serif',
  },
  signupErrorText: {
    color: APP_CONSTANTS.COLORS.ERROR,
    marginTop: isWeb ? 8 : 6,
    marginBottom: isWeb ? 20 : 16,
    textAlign: 'center',
    fontSize: isWeb ? 15 : 14,
    fontWeight: '500',
    width: '100%',
    paddingHorizontal: isWeb ? 12 : 10,
    fontFamily: 'Inter, sans-serif',
  },
  signupLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  signupInlineLoader: {
    marginLeft: isWeb ? 12 : 8,
  },
  signupFeedbackText: {
    fontSize: isWeb ? 13 : 12,
    marginTop: isWeb ? 6 : 4,
    paddingLeft: isWeb ? 4 : 2,
    fontFamily: 'Inter, sans-serif',
  },
  signupFeedbackTextValid: {
    color: APP_CONSTANTS.COLORS.SUCCESS || '#28a745',
  },
  signupFeedbackTextError: {
    color: APP_CONSTANTS.COLORS.ERROR,
  },
  signupStickyButtonContainer: {
    position: 'absolute',
    bottom: isWeb ? 40 : 20,
    left: isWeb ? 40 : 24,
    right: isWeb ? 40 : 24,
    backgroundColor: 'transparent',
  },
  signupStreamingServicesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: isWeb ? 24 : 20,
    gap: isWeb ? 16 : 12,
  },
  signupServiceCard: {
    width: isWeb ? '48%' : '48%',
    aspectRatio: 1,
    backgroundColor: 'white',
    borderRadius: isWeb ? 16 : 12,
    borderWidth: 1.5,
    borderColor: APP_CONSTANTS.COLORS.BORDER,
    padding: isWeb ? 16 : 12,
    marginBottom: isWeb ? 20 : 16,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: isWeb ? 4 : 2 },
    shadowOpacity: 0.08,
    shadowRadius: isWeb ? 8 : 4,
  },
  signupSelectedServiceCard: {
    borderColor: APP_CONSTANTS.COLORS.PRIMARY,
    backgroundColor: `${APP_CONSTANTS.COLORS.PRIMARY}10`,
    elevation: 4,
    shadowColor: APP_CONSTANTS.COLORS.PRIMARY,
    shadowOpacity: 0.15,
    shadowRadius: isWeb ? 12 : 8,
  },
  signupServiceIconContainer: {
    width: isWeb ? 72 : 60,
    height: isWeb ? 72 : 60,
    borderRadius: isWeb ? 36 : 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: isWeb ? 16 : 12,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: isWeb ? 4 : 2 },
    shadowOpacity: 0.1,
    shadowRadius: isWeb ? 8 : 4,
  },
  signupServiceName: {
    fontSize: isWeb ? 14 : 13,
    color: APP_CONSTANTS.COLORS.TEXT_SECONDARY,
    fontWeight: '500',
    textAlign: 'center',
    fontFamily: 'Inter, sans-serif',
  },
  signupCheckmarkBadge: {
    position: 'absolute',
    top: isWeb ? 12 : 8,
    right: isWeb ? 12 : 8,
    backgroundColor: APP_CONSTANTS.COLORS.PRIMARY,
    borderRadius: isWeb ? 16 : 12,
    width: isWeb ? 32 : 24,
    height: isWeb ? 32 : 24,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
    shadowColor: APP_CONSTANTS.COLORS.PRIMARY,
    shadowOffset: { width: 0, height: isWeb ? 4 : 2 },
    shadowOpacity: 0.3,
    shadowRadius: isWeb ? 8 : 4,
  },
  signupSubscriptionOptionsContainer: {
    width: '100%',
    marginTop: isWeb ? 12 : 10,
    marginBottom: isWeb ? 24 : 20,
    gap: isWeb ? 20 : 16,
  },
  signupSubscriptionCard: {
    backgroundColor: 'white',
    borderRadius: isWeb ? 16 : 12,
    borderWidth: 1.5,
    borderColor: APP_CONSTANTS.COLORS.BORDER,
    padding: isWeb ? 24 : 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: isWeb ? 4 : 2 },
    shadowOpacity: 0.08,
    shadowRadius: isWeb ? 8 : 4,
    elevation: 2,
    width: '100%',
    position: 'relative',
  },
  signupSelectedSubscriptionCard: {
    borderColor: APP_CONSTANTS.COLORS.PRIMARY,
    backgroundColor: `${APP_CONSTANTS.COLORS.PRIMARY}0A`,
    shadowColor: APP_CONSTANTS.COLORS.PRIMARY,
    shadowOpacity: 0.15,
    shadowRadius: isWeb ? 12 : 8,
    elevation: 4,
  },
  signupPlanHeader: {
    marginBottom: isWeb ? 20 : 16,
  },
  signupPlanTitle: {
    fontSize: isWeb ? 24 : 20,
    fontWeight: '700',
    color: APP_CONSTANTS.COLORS.TEXT_PRIMARY,
    marginBottom: isWeb ? 6 : 4,
    fontFamily: 'Inter, sans-serif',
  },
  signupPlanPrice: {
    fontSize: isWeb ? 20 : 16,
    fontWeight: '600',
    color: APP_CONSTANTS.COLORS.PRIMARY,
    marginBottom: isWeb ? 8 : 6,
    fontFamily: 'Inter, sans-serif',
  },
  signupPlanDescription: {
    fontSize: isWeb ? 15 : 14,
    color: APP_CONSTANTS.COLORS.TEXT_SECONDARY,
    lineHeight: isWeb ? 22 : 20,
    fontFamily: 'Inter, sans-serif',
  },
  signupBusinessTypeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: isWeb ? 12 : 10,
    gap: isWeb ? 12 : 8,
  },
  signupBusinessTypeOption: {
    paddingHorizontal: isWeb ? 20 : 16,
    paddingVertical: isWeb ? 12 : 10,
    borderRadius: isWeb ? 24 : 20,
    borderWidth: 1,
    borderColor: APP_CONSTANTS.COLORS.BORDER,
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: isWeb ? 2 : 1 },
    shadowOpacity: 0.05,
    shadowRadius: isWeb ? 4 : 2,
    elevation: 1,
  },
  signupBusinessTypeSelected: {
    backgroundColor: `${APP_CONSTANTS.COLORS.PRIMARY}20`,
    borderColor: APP_CONSTANTS.COLORS.PRIMARY,
    shadowColor: APP_CONSTANTS.COLORS.PRIMARY,
    shadowOpacity: 0.15,
    shadowRadius: isWeb ? 8 : 4,
    elevation: 2,
  },
  signupBusinessTypeText: {
    fontSize: isWeb ? 15 : 14,
    color: APP_CONSTANTS.COLORS.TEXT_PRIMARY,
    fontWeight: '500',
    fontFamily: 'Inter, sans-serif',
  },
  signupBusinessTypeTextSelected: {
    color: APP_CONSTANTS.COLORS.PRIMARY,
    fontWeight: '600',
  },
  signupLogoContainer: {
    alignItems: 'center',
    marginVertical: isWeb ? 20 : 16,
  },
  signupLogoPreview: {
    width: isWeb ? 120 : 100,
    height: isWeb ? 150 : 125,
    borderRadius: isWeb ? 16 : 12,
    marginBottom: isWeb ? 20 : 16,
    backgroundColor: '#e0e0e0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: isWeb ? 8 : 4 },
    shadowOpacity: 0.1,
    shadowRadius: isWeb ? 16 : 8,
    elevation: 4,
  },
  signupLogoPlaceholder: {
    width: isWeb ? 120 : 100,
    height: isWeb ? 150 : 125,
    borderRadius: isWeb ? 16 : 12,
    backgroundColor: `${APP_CONSTANTS.COLORS.BORDER}30`,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: isWeb ? 4 : 2 },
    shadowOpacity: 0.05,
    shadowRadius: isWeb ? 8 : 4,
    elevation: 2,
  },
  signupGoogleSignInButton: {
    backgroundColor: 'white',
    paddingVertical: isWeb ? 16 : 14,
    paddingHorizontal: isWeb ? 24 : 20,
    borderRadius: isWeb ? 16 : 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: isWeb ? 24 : 20,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: isWeb ? 6 : 4 },
    shadowOpacity: 0.1,
    shadowRadius: isWeb ? 12 : 8,
    borderWidth: 1,
    borderColor: APP_CONSTANTS.COLORS.BORDER,
  },
  signupGoogleSignInText: {
    color: APP_CONSTANTS.COLORS.TEXT_PRIMARY,
    fontWeight: '600',
    fontSize: isWeb ? 16 : 14,
    fontFamily: 'Inter, sans-serif',
  },
  signupStepsSlider: {
    width: '100%',
    minHeight: '100%',
  },
  signupScrollContentContainer: {
    flexGrow: 1,
    paddingHorizontal: isWeb ? 40 : 20,
    paddingBottom: isWeb ? 100 : 80,
    width: '100%',
    maxWidth: isWeb ? 800 : '100%',
    minHeight: isWeb ? height * 0.8 : '100%',
    alignItems: 'stretch',
  },

  // Web-specific wide form wrapper and sticky button
  formWrapperWeb: {
    width: '100%',
    maxWidth: 520,
    marginHorizontal: 'auto',
    backgroundColor: 'transparent',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
    minHeight: isWeb ? height * 0.8 : undefined,
    paddingTop: isWeb ? 48 : 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
  },
  stickyButtonWeb: {
    position: isWeb ? 'absolute' : 'relative',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 100,
    backgroundColor: 'rgba(255,255,255,0.95)',
    paddingTop: isWeb ? 24 : 0,
    paddingBottom: isWeb ? 24 : 0,
    paddingLeft: 0,
    paddingRight: 0,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
}); 