import { StyleSheet, Platform } from 'react-native';
import { APP_CONSTANTS } from '@/config/constants';

// ChatCard Styles
export const chatCardStyles = StyleSheet.create({
    container: {
        backgroundColor: "white",
        borderRadius: 12,
        overflow: "hidden",
        marginBottom: 8,
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: "#E5E7EB",
    },
    pinned: {
        borderLeftWidth: 3,
        borderLeftColor: "#F59E0B", // Amber color for pinned
    },
    unread: {
        backgroundColor: "rgba(59, 130, 246, 0.02)", // Very subtle background for unread
        borderColor: "rgba(59, 130, 246, 0.1)",
    },
    content: {
        flexDirection: "row",
        paddingVertical: 12,
        paddingHorizontal: 12,
        alignItems: "center",
    },
    avatarContainer: {
        marginRight: 12,
        position: 'relative',
    },
    avatar: {
        width: 52,
        height: 52,
        borderRadius: 26,
        backgroundColor: '#E5E7EB',
    },
    onlineIndicator: {
        position: 'absolute',
        top: 0,
        right: 0,
        width: 16,
        height: 16,
        borderRadius: 8,
        backgroundColor: '#10B981', // Green color for unread indicator
        borderWidth: 2,
        borderColor: 'white',
    },
    chatInfo: {
        flex: 1,
        justifyContent: 'center',
    },
    nameTimeRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: 'center',
        marginBottom: 3,
    },
    name: {
        fontWeight: "600",
        fontSize: 15,
        color: "#1F2937",
        flexShrink: 1,
        marginRight: 5,
    },
    nameUnread: {
        fontWeight: "bold", // Make name bold if unread
        color: "#111827",
    },
    time: {
        fontSize: 12,
        color: "#6B7280",
        marginLeft: 'auto',
    },
    timeUnread: {
        color: "#374151", // Darker time text if unread
        fontWeight: "500",
    },
    message: {
        fontSize: 14,
        color: "#4B5563",
    },
    messageUnread: {
        color: "#1F2937", // Darker message text if unread
        fontWeight: "500",
    },
    membersRow: {
        marginTop: 3,
    },
    members: {
        fontSize: 12,
        color: "#9CA3AF",
        fontStyle: 'italic',
    },
    badgeContainer: {
        marginLeft: 8,
        width: 28, // Fixed width container for alignment
        alignItems: 'center',
        justifyContent: 'center',
    },
    badge: {
        backgroundColor: "#3B82F6",
        borderRadius: 12,
        minWidth: 24,
        height: 24,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 6,
    },
    badgeText: {
        color: "white",
        fontSize: 11,
        fontWeight: "bold",
    },
    pinIcon: {
        opacity: 0.6,
    }
});

// ChatPanel Styles
export const chatPanelStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
        borderLeftWidth: 1,
        borderLeftColor: '#E5E7EB',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
        backgroundColor: '#FFFFFF',
    },
    backButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#F3F4F6',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    headerContent: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#1F2937',
    },
    loadingText: {
        marginLeft: 8,
        fontSize: 14,
        color: '#6B7280',
    },
    messagesContainer: {
        flex: 1,
        backgroundColor: '#F9FAFB',
    },
    messagesScroll: {
        flex: 1,
    },
    messagesContent: {
        padding: 16,
        flexGrow: 1,
        justifyContent: 'center',
    },
    placeholderMessage: {
        alignItems: 'center',
        padding: 32,
    },
    placeholderText: {
        fontSize: 16,
        fontWeight: '500',
        color: '#374151',
        textAlign: 'center',
        marginBottom: 8,
    },
    placeholderSubtext: {
        fontSize: 14,
        color: '#6B7280',
        textAlign: 'center',
        lineHeight: 20,
    },
    inputContainer: {
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 16,
        paddingVertical: 12,
    },
    inputWrapper: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        backgroundColor: '#F3F4F6',
        borderRadius: 20,
        paddingHorizontal: 16,
        paddingVertical: 8,
        minHeight: 44,
    },
    textInput: {
        flex: 1,
        fontSize: 15,
        color: '#1F2937',
        maxHeight: 100,
        paddingVertical: 4,
    },
    sendButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 8,
    },
    sendButtonActive: {
        backgroundColor: APP_CONSTANTS?.COLORS?.PRIMARY || '#3B82F6',
    },
    sendButtonInactive: {
        backgroundColor: '#E5E7EB',
    },
    emptyState: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 32,
    },
    emptyStateTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#374151',
        marginTop: 16,
        textAlign: 'center',
    },
    emptyStateSubtitle: {
        fontSize: 14,
        color: '#6B7280',
        marginTop: 8,
        textAlign: 'center',
        lineHeight: 20,
    },
});

// ChatsTabs Styles
export const chatsTabsStyles = StyleSheet.create({
    container: { 
        flex: 1, 
    },
    centered: { 
        flex: 1, 
        justifyContent: 'center', 
        alignItems: 'center', 
        padding: 20, 
    },
    errorText: { 
        color: '#DC2626', 
        textAlign: 'center', 
        marginBottom: 15 
    },
    retryButton: { 
        flexDirection: 'row', 
        alignItems: 'center', 
        backgroundColor: APP_CONSTANTS.COLORS.PRIMARY, 
        paddingVertical: 8, 
        paddingHorizontal: 15, 
        borderRadius: 6, 
    },
    retryButtonText: { 
        color: 'white', 
        fontWeight: '500', 
        fontSize: 14, 
        marginLeft: 6, 
    },
    emptyText: { 
        textAlign: 'center', 
        color: '#6B7280', 
        marginTop: 40, 
        fontSize: 15, 
    },
    tabsContainer: { 
        flexDirection: 'row', 
        backgroundColor: 'rgba(59, 130, 246, 0.05)', 
        borderRadius: 10, 
        padding: 4, 
        marginBottom: 8, 
    },
    tabButton: { 
        flex: 1, 
        flexDirection: 'row', 
        alignItems: 'center', 
        justifyContent: 'center', 
        paddingVertical: 10, 
        borderRadius: 8, 
    },
    activeTabButton: { 
        backgroundColor: "white", 
        shadowColor: "#000", 
        shadowOffset: { width: 0, height: 1 }, 
        shadowOpacity: 0.05, 
        shadowRadius: 2, 
        elevation: 2, 
    },
    tabIcon: { 
        marginRight: 6, 
    },
    tabText: { 
        fontSize: 14, 
        color: "#6B7280", 
        fontWeight: '500' 
    },
    activeTabText: { 
        color: APP_CONSTANTS.COLORS.PRIMARY, 
        fontWeight: "600", 
    },
    subTabsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginBottom: 12,
        paddingHorizontal: 16,
    },
    subTabButton: {
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 18,
        borderWidth: 1,
        borderColor: 'transparent',
    },
    activeSubTabButton: {
        backgroundColor: APP_CONSTANTS.COLORS.PRIMARY_LIGHT || '#E0E7FF',
        borderColor: APP_CONSTANTS.COLORS.PRIMARY || '#A5B4FC',
    },
    subTabText: {
        fontSize: 13,
        fontWeight: '500',
        color: APP_CONSTANTS.COLORS.TEXT_SECONDARY || '#4B5563',
    },
    activeSubTabText: {
        color: APP_CONSTANTS.COLORS.PRIMARY_DARK || APP_CONSTANTS.COLORS.PRIMARY || '#3730A3',
        fontWeight: '600',
    },
    tabContent: { 
        flex: 1, 
    },
    listContent: { 
        paddingTop: 4, 
        paddingBottom: 16, 
    },
});

// ChatProfileSheet Styles
export const chatProfileSheetStyles = StyleSheet.create({
    modalContainer: {
        flex: 1,
        justifyContent: "flex-end",
        backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
    sheetContainer: {
        backgroundColor: "white",
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        height: "85%",
        paddingHorizontal: 20,
        paddingTop: 12,
        paddingBottom: 20,
    },
    handle: {
        width: 40,
        height: 4,
        borderRadius: 2,
        backgroundColor: "#E5E7EB",
        alignSelf: "center",
        marginBottom: 12,
    },
    closeButton: {
        position: "absolute",
        right: 20,
        top: 12,
        zIndex: 1,
    },
    content: {
        paddingBottom: 40,
        paddingTop: 20,
    },
    profileContainer: {
        alignItems: "center",
    },
    avatar: {
        width: 80,
        height: 80,
        borderRadius: 40,
        marginBottom: 16,
    },
    avatarFallback: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: "rgba(59, 130, 246, 0.1)",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 16,
    },
    avatarText: {
        fontSize: 32,
        fontWeight: "600",
        color: "#3B82F6",
    },
    name: {
        fontSize: 22,
        fontWeight: "bold",
        marginBottom: 16,
        color: "#1F2937",
    },
    section: {
        width: "100%",
        marginBottom: 16,
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: "500",
        color: "#6B7280",
        marginBottom: 8,
    },
    tagsContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        marginHorizontal: -4,
    },
    tag: {
        backgroundColor: "rgba(59, 130, 246, 0.1)",
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 16,
        margin: 4,
    },
    tagText: {
        color: "#1E3A8A",
        fontSize: 14,
    },
    genreTag: {
        backgroundColor: "rgba(96, 165, 250, 0.1)",
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 16,
        margin: 4,
    },
    genreTagText: {
        color: "#3B82F6",
        fontSize: 14,
    },
    messageButton: {
        backgroundColor: "#3B82F6",
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 8,
        width: "100%",
        alignItems: "center",
        marginTop: 24,
    },
    messageButtonText: {
        color: "white",
        fontWeight: "600",
        fontSize: 16,
    },
});

// ConversationStarters Styles
export const conversationStartersStyles = StyleSheet.create({
    container: {
        marginTop: 16,
        width: "100%",
    },
    section: {
        marginBottom: 16,
    },
    headerContainer: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 8,
    },
    icon: {
        marginRight: 4,
    },
    sectionHeader: {
        fontSize: 14,
        fontWeight: "500",
        color: "#6B7280",
    },
    starterCard: {
        backgroundColor: "rgba(59, 130, 246, 0.1)",
        borderRadius: 8,
        padding: 12,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: "rgba(59, 130, 246, 0.2)",
    },
    starterText: {
        fontSize: 14,
        color: "#1E3A8A",
    },
    musicStarterCard: {
        backgroundColor: "rgba(96, 165, 250, 0.1)",
        borderRadius: 8,
        padding: 12,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: "rgba(96, 165, 250, 0.2)",
    },
    musicStarterText: {
        fontSize: 14,
        color: "#3B82F6",
    },
});

// ChatPanelWrapper Styles
export const chatPanelWrapperStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
        borderLeftWidth: 1,
        borderLeftColor: '#E5E7EB',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
    },
    loadingText: {
        marginTop: 12,
        fontSize: 14,
        color: '#6B7280',
    },
    emptyState: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 32,
    },
    emptyStateTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#374151',
        marginTop: 16,
        textAlign: 'center',
    },
    emptyStateSubtitle: {
        fontSize: 14,
        color: '#6B7280',
        marginTop: 8,
        textAlign: 'center',
        lineHeight: 20,
    },
});

// ChatsScreen Styles
export const chatsScreenStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F9FAFB',
    },
    // Web-specific styles for 3-panel layout
    webContainer: {
        flex: 1,
        flexDirection: 'row',
        backgroundColor: '#F9FAFB',
    },
    webLeftPanel: {
        width: 400,
        backgroundColor: '#FFFFFF',
        borderRightWidth: 1,
        borderRightColor: '#E5E7EB',
        flexDirection: 'column',
    },
    webRightPanel: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    webChatListContent: {
        flex: 1,
        paddingHorizontal: 16,
        paddingTop: 0,
    },
    header: {
        paddingTop: Platform.OS === 'android' ? 15 : 10,
        paddingBottom: 12,
        paddingHorizontal: 16,
        backgroundColor: 'white',
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
    },
    headerTitleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    titleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    headerIcon: {
        marginRight: 10,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1F2937',
    },
    createGroupButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(59, 130, 246, 0.1)',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: 'rgba(59, 130, 246, 0.2)',
    },
    searchContainer: {
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: 'white',
    },
    searchInputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F3F4F6',
        borderRadius: 10,
        paddingHorizontal: 12,
        height: 42,
    },
    searchIcon: {
        marginRight: 8,
    },
    searchInput: {
        flex: 1,
        fontSize: 15,
        color: '#1F2937',
        paddingVertical: 8,
    },
    clearButton: {
        padding: 4,
        marginLeft: 4,
    },
    content: {
        flex: 1,
        paddingHorizontal: Platform.OS === 'web' ? 0 : 16,
        paddingTop: 0,
    },
    // Keep loading/error styles if they were used elsewhere or needed as fallbacks
    centered: { 
        flex: 1, 
        justifyContent: 'center', 
        alignItems: 'center', 
        padding: 20 
    },
    loadingText: { 
        marginTop: 10, 
        fontSize: 16, 
        color: '#6B7280' 
    },
    errorText: { 
        marginTop: 15, 
        fontSize: 18, 
        fontWeight: '600', 
        color: '#DC2626', 
        textAlign: 'center' 
    },
    errorSubText: { 
        marginTop: 8, 
        fontSize: 14, 
        color: '#4B5563', 
        textAlign: 'center', 
        maxWidth: '90%' 
    },
    retryButton: { 
        flexDirection: 'row', 
        alignItems: 'center', 
        marginTop: 25, 
        backgroundColor: APP_CONSTANTS?.COLORS?.PRIMARY || '#3B82F6', 
        paddingVertical: 12, 
        paddingHorizontal: 25, 
        borderRadius: 8 
    },
    retryButtonText: { 
        color: 'white', 
        fontWeight: '600', 
        fontSize: 15, 
        marginLeft: 8 
    },
});

// IndividualChatScreen Styles - Modern & Consistent Design
export const individualChatScreenStyles = StyleSheet.create({
    safeArea: { 
        flex: 1, 
        backgroundColor: APP_CONSTANTS?.COLORS?.BACKGROUND_LIGHT || '#F9FAFB', 
    },
    customHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: Platform.OS === 'web' ? 24 : 16,
        paddingVertical: Platform.OS === 'web' ? 16 : 12,
        backgroundColor: APP_CONSTANTS?.COLORS?.WHITE || '#FFFFFF',
        borderBottomWidth: 1,
        borderBottomColor: APP_CONSTANTS?.COLORS?.BORDER_LIGHT || '#F3F4F6',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 2,
    },
    headerBackButton: {
        padding: Platform.OS === 'web' ? 8 : 5,
        borderRadius: Platform.OS === 'web' ? 8 : 6,
        backgroundColor: 'transparent',
    },
    headerTitleContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginHorizontal: Platform.OS === 'web' ? 16 : 8,
    },
    headerProfileImage: {
        width: Platform.OS === 'web' ? 40 : 34,
        height: Platform.OS === 'web' ? 40 : 34,
        borderRadius: Platform.OS === 'web' ? 20 : 17,
        marginRight: Platform.OS === 'web' ? 12 : 10,
        borderWidth: 2,
        borderColor: APP_CONSTANTS?.COLORS?.BORDER_LIGHT || '#F3F4F6',
    },
    headerTitleTextContainer: {
        alignItems: 'flex-start',
        justifyContent: 'center',
    },
    headerTitle: {
        fontSize: Platform.OS === 'web' ? 18 : 17,
        fontWeight: '600',
        color: APP_CONSTANTS?.COLORS?.TEXT_PRIMARY || '#1F2937',
        marginBottom: Platform.OS === 'web' ? 2 : 1,
    },
    headerSubtitle: {
        fontSize: Platform.OS === 'web' ? 13 : 12,
        color: APP_CONSTANTS?.COLORS?.TEXT_SECONDARY || '#6B7280',
        marginTop: Platform.OS === 'web' ? 2 : 1,
    },
    keyboardAvoidingContainer: { 
        flex: 1, 
    },
    centered: { 
        flex: 1, 
        justifyContent: 'center', 
        alignItems: 'center', 
        padding: Platform.OS === 'web' ? 32 : 20, 
    },
    errorText: { 
        color: APP_CONSTANTS?.COLORS?.ERROR || '#DC2626', 
        fontSize: Platform.OS === 'web' ? 16 : 14, 
        textAlign: 'center', 
        marginTop: 10,
        fontWeight: '500',
    },
    infoText: { 
        color: APP_CONSTANTS?.COLORS?.TEXT_SECONDARY || '#6B7280', 
        fontSize: Platform.OS === 'web' ? 15 : 14, 
        textAlign: 'center', 
        marginTop: 8,
        lineHeight: Platform.OS === 'web' ? 22 : 20,
    },
    errorBanner: { 
        backgroundColor: 'rgba(239, 68, 68, 0.08)', 
        paddingVertical: Platform.OS === 'web' ? 12 : 8, 
        paddingHorizontal: Platform.OS === 'web' ? 20 : 15,
        borderRadius: Platform.OS === 'web' ? 8 : 6,
        marginHorizontal: Platform.OS === 'web' ? 16 : 12,
        marginVertical: Platform.OS === 'web' ? 8 : 6,
    },
    errorBannerText: { 
        color: APP_CONSTANTS?.COLORS?.ERROR || '#B91C1C', 
        fontSize: Platform.OS === 'web' ? 14 : 13, 
        textAlign: 'center',
        fontWeight: '500',
    },
    noMessagesText: { 
        color: APP_CONSTANTS?.COLORS?.TEXT_SECONDARY || '#6B7280', 
        fontSize: Platform.OS === 'web' ? 16 : 14, 
        marginTop: Platform.OS === 'web' ? 40 : 30,
        textAlign: 'center',
        fontStyle: 'italic',
    },
    messageList: { 
        flex: 1, 
        paddingHorizontal: Platform.OS === 'web' ? 16 : 10, 
        backgroundColor: APP_CONSTANTS?.COLORS?.BACKGROUND_LIGHT || '#F9FAFB', 
    },
    messageListContent: { 
        paddingVertical: Platform.OS === 'web' ? 16 : 10, 
        flexGrow: 1, 
        justifyContent: 'flex-end',
        paddingHorizontal: Platform.OS === 'web' ? 8 : 0,
    },
    messageRow: { 
        flexDirection: 'row', 
        marginVertical: Platform.OS === 'web' ? 6 : 4, 
        alignItems: 'flex-end', 
    },
    messageRowSent: { 
        justifyContent: 'flex-end', 
        marginLeft: Platform.OS === 'web' ? '25%' : '20%', 
    },
    messageRowReceived: { 
        justifyContent: 'flex-start', 
        marginRight: Platform.OS === 'web' ? '25%' : '20%', 
    },
    messageContentContainer: {
        maxWidth: '100%',
    },
    messageBubble: {
        borderRadius: Platform.OS === 'web' ? 20 : 18,
        minWidth: Platform.OS === 'web' ? 40 : 30,
        marginBottom: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: Platform.OS === 'web' ? 2 : 1 },
        shadowOpacity: Platform.OS === 'web' ? 0.08 : 0.1,
        shadowRadius: Platform.OS === 'web' ? 4 : 2,
        elevation: Platform.OS === 'web' ? 3 : 2,
    },
    messageBubbleSent: {
        backgroundColor: APP_CONSTANTS?.COLORS?.PRIMARY || '#3B82F6',
        borderBottomRightRadius: Platform.OS === 'web' ? 6 : 4,
        alignSelf: 'flex-end',
        paddingVertical: Platform.OS === 'web' ? 12 : 10,
        paddingHorizontal: Platform.OS === 'web' ? 16 : 14,
    },
    messageBubbleReceived: {
        backgroundColor: APP_CONSTANTS?.COLORS?.WHITE || '#FFFFFF',
        borderBottomLeftRadius: Platform.OS === 'web' ? 6 : 4,
        alignSelf: 'flex-start',
        paddingVertical: Platform.OS === 'web' ? 12 : 10,
        paddingHorizontal: Platform.OS === 'web' ? 16 : 14,
        borderWidth: 1,
        borderColor: APP_CONSTANTS?.COLORS?.BORDER_LIGHT || '#F3F4F6',
    },
    messageText: { 
        fontSize: Platform.OS === 'web' ? 16 : 15, 
        lineHeight: Platform.OS === 'web' ? 24 : 21, 
        flexShrink: 1,
    },
    messageTextSent: { 
        color: '#FFFFFF',
        fontWeight: Platform.OS === 'web' ? '400' : 'normal',
    },
    messageTextReceived: { 
        color: APP_CONSTANTS?.COLORS?.TEXT_PRIMARY || '#1F2937',
        fontWeight: Platform.OS === 'web' ? '400' : 'normal',
    },
    inputToolbar: { 
        flexDirection: 'row', 
        alignItems: 'flex-end', 
        paddingVertical: Platform.OS === 'web' ? 16 : 12, 
        paddingHorizontal: Platform.OS === 'web' ? 20 : 16, 
        borderTopWidth: 1, 
        borderTopColor: APP_CONSTANTS?.COLORS?.BORDER_LIGHT || '#F3F4F6', 
        backgroundColor: APP_CONSTANTS?.COLORS?.WHITE || '#FFFFFF',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -1 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 2,
    },
    textInput: { 
        flex: 1, 
        minHeight: Platform.OS === 'web' ? 48 : 44, 
        maxHeight: 120, 
        backgroundColor: APP_CONSTANTS?.COLORS?.BACKGROUND_LIGHT || '#F9FAFB', 
        borderRadius: Platform.OS === 'web' ? 24 : 22, 
        paddingHorizontal: Platform.OS === 'web' ? 18 : 16, 
        paddingVertical: Platform.OS === 'ios' ? 12 : 10, 
        fontSize: Platform.OS === 'web' ? 16 : 15, 
        marginHorizontal: Platform.OS === 'web' ? 12 : 8, 
        color: APP_CONSTANTS?.COLORS?.TEXT_PRIMARY || '#1F2937',
        borderWidth: 1,
        borderColor: APP_CONSTANTS?.COLORS?.BORDER_LIGHT || '#F3F4F6',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    sendButton: { 
        backgroundColor: APP_CONSTANTS?.COLORS?.PRIMARY || '#3B82F6', 
        width: Platform.OS === 'web' ? 48 : 44, 
        height: Platform.OS === 'web' ? 48 : 44, 
        borderRadius: Platform.OS === 'web' ? 24 : 22, 
        justifyContent: 'center', 
        alignItems: 'center',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    sendButtonDisabled: { 
        backgroundColor: APP_CONSTANTS?.COLORS?.DISABLED || '#9CA3AF',
        shadowOpacity: 0,
        elevation: 0,
    },

    blockedText: {
        color: '#9CA3AF',
    },
    muteIcon: {
        marginLeft: 6,
    },
    timeText: {
        fontSize: 11,
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
    },
    timeTextSent: {
        alignSelf: 'flex-end',
        marginRight: 8,
        marginTop: 4,
        color: '#9CA3AF',
    },
    timeTextReceived: {
        alignSelf: 'flex-start',
        marginLeft: 8,
        marginTop: 4,
        color: '#9CA3AF',
    },
    timeTextInsideBubble: {
        fontSize: 10,
        marginLeft: 8,
        alignSelf: 'flex-end',
        lineHeight: 15,
    },
    timeTextInsideSentBubble: { 
        color: 'rgba(255, 255, 255, 0.7)' 
    },
    timeTextInsideReceivedBubble: { 
        color: '#6B7280'
    },
    timeAndEditContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
        marginTop: 4,
        minHeight: 16,
    },
    sectionHeader: {
        alignItems: 'center',
        paddingVertical: 8,
        paddingHorizontal: 16,
        backgroundColor: '#F9FAFB',
        zIndex: 100,
        borderBottomWidth: 0.5,
        borderBottomColor: 'rgba(0,0,0,0.05)',
    },
    sectionHeaderText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#6B7280',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    imageBubble: {
        borderRadius: 18,
        overflow: 'hidden',
        padding: 0,
        backgroundColor: 'transparent',
        alignSelf: 'flex-start',
        maxWidth: 220,
        maxHeight: 220,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    messageBubbleSentImage: {
        alignSelf: 'flex-end',
        backgroundColor: 'transparent',
        borderBottomRightRadius: 4,
    },
    messageBubbleReceivedImage: {
        alignSelf: 'flex-start',
        backgroundColor: 'transparent',
        borderBottomLeftRadius: 4,
    },
    chatImage: {
        width: 210,
        height: 210,
        borderRadius: 16,
    },
    imageErrorOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.4)',
        borderRadius: 16,
    },
    imageErrorText: {
        color: '#FFFFFF',
        fontSize: 12,
        marginTop: 4,
        textAlign: 'center',
    },
    attachButton: {
        width: 44,
        height: 44,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 22,
    },
    // Additional styles that IndividualChatScreen needs
    deletedMessageBubble: {
        paddingVertical: 10,
        paddingHorizontal: 14,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F3F4F6',
        opacity: 0.8,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    deletedMessageText: {
        fontSize: 14,
        fontStyle: 'italic',
        color: '#6B7280',
    },
    messageRowTouchable: {
        flexDirection: 'row',
        marginVertical: 4,
        alignItems: 'flex-end',
    },
    sharedEventMessageBubble: {
        padding: 14,
        maxWidth: 300,
    },
    sharedEventPreview: {
        marginTop: 10,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.08)',
        overflow: 'hidden',
        backgroundColor: '#FFFFFF',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    sharedEventPreviewImage: {
        width: '100%',
        height: 140,
        backgroundColor: '#F3F4F6',
    },
    sharedEventPreviewContent: {
        padding: 12,
    },
    sharedEventPreviewTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 4,
    },
    sharedEventPreviewDetails: {
        fontSize: 13,
        color: '#6B7280',
        marginBottom: 2,
    },
    sharedEventPreviewDisabled: {
        opacity: 0.5,
    },
    sharedEventPreviewImageDisabled: {
        backgroundColor: '#F3F4F6',
    },
    eventOverOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.4)',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 16,
    },
    eventOverText: {
        color: '#FFFFFF',
        fontSize: 12,
        marginTop: 4,
        textAlign: 'center',
    },
    eventOverTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 2,
    },
    eventOverDetails: {
        fontSize: 13,
        color: '#6B7280',
        marginBottom: 1,
    },
    editedIndicator: {
        fontSize: 10,
        fontStyle: 'italic',
        marginRight: 6,
    },
    editedIndicatorSent: {
        color: 'rgba(255, 255, 255, 0.7)',
    },
    editedIndicatorReceived: {
        color: '#6B7280',
    },
    editedIndicatorImage: {
        position: 'absolute',
        bottom: 8,
        right: 8,
        backgroundColor: 'rgba(0,0,0,0.6)',
        color: 'white',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 4,
        fontSize: 9,
    },
    replyPreviewContainer: {
        flexDirection: 'row',
        backgroundColor: 'rgba(0,0,0,0.04)',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderTopLeftRadius: 12,
        borderTopRightRadius: 12,
        marginBottom: -2,
        maxWidth: '90%',
    },
    replyPreviewSent: {
        alignSelf: 'flex-end',
        borderLeftColor: APP_CONSTANTS?.COLORS?.PRIMARY || '#3B82F6',
        borderLeftWidth: 3,
    },
    replyPreviewReceived: {
        alignSelf: 'flex-start',
        borderLeftColor: '#A0AEC0',
        borderLeftWidth: 3,
    },
    replyPreviewBorder: {
    },
    replyPreviewContent: {
        marginLeft: 8,
        flexShrink: 1,
    },
    replyPreviewSenderName: {
        fontSize: 12,
        fontWeight: '600',
        color: '#4B5563',
        marginBottom: 2,
    },
    replyPreviewText: {
        fontSize: 12,
        color: '#6B7280',
    },
    highlightedImageBubble: {
        borderWidth: 2,
        borderColor: 'rgba(59, 130, 246, 0.3)',
        shadowColor: '#3B82F6',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 4,
    },
    // Additional styles that IndividualChatScreen needs
    onlineIndicator: {
        position: 'absolute',
        bottom: -2,
        right: -2,
        width: 16,
        height: 16,
        borderRadius: 8,
        backgroundColor: '#22C55E',
        borderWidth: 2,
        borderColor: '#FFFFFF',
        justifyContent: 'center',
        alignItems: 'center',
    },
    sharedEventContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
        backgroundColor: '#F8F9FA',
    },
    sharedEventContent: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    sharedEventImage: {
        width: 50,
        height: 50,
        borderRadius: 10,
        marginRight: 12,
    },
    sharedEventInfo: {
        flex: 1,
    },
    sharedEventTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 2,
    },
    sharedEventDetails: {
        fontSize: 13,
        color: '#6B7280',
        marginBottom: 1,
    },
    sharedEventCloseButton: {
        padding: 8,
        borderRadius: 16,
        backgroundColor: '#FFFFFF',
    },
    // Additional conversation starter styles
    startersLoadingContainer: {
        alignItems: 'center',
        paddingVertical: 20,
    },
    startersLoadingText: {
        marginTop: 8,
        fontSize: 14,
        color: '#6B7280',
    },
    startersOuterContainer: {
        marginTop: 16,
        width: '100%',
    },
    startersTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 12,
    },
    startersNavigationContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    starterNavButton: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        backgroundColor: 'rgba(59, 130, 246, 0.1)',
        borderWidth: 1,
        borderColor: 'rgba(59, 130, 246, 0.2)',
    },
    starterNavButtonDisabled: {
        backgroundColor: 'rgba(156, 163, 175, 0.1)',
        borderColor: 'rgba(156, 163, 175, 0.2)',
    },
    starterButton: {
        backgroundColor: 'rgba(59, 130, 246, 0.1)',
        borderRadius: 8,
        padding: 12,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: 'rgba(59, 130, 246, 0.2)',
    },
    starterText: {
        fontSize: 14,
        color: '#1E3A8A',
    },
    // Additional missing styles for IndividualChatScreen
    starterCounterText: {
        fontSize: 12,
        color: '#6B7280',
        marginTop: 4,
    },
    typingIndicatorContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 8,
    },
    typingIndicatorText: {
        fontSize: 14,
        color: '#6B7280',
        fontStyle: 'italic',
        marginLeft: 8,
    },
    newMessagesDivider: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 16,
        paddingHorizontal: 16,
    },
    newMessagesDividerLine: {
        flex: 1,
        height: 1,
        backgroundColor: '#E5E7EB',
    },
    newMessagesDividerText: {
        fontSize: 12,
        color: '#6B7280',
        marginHorizontal: 12,
        fontWeight: '500',
    },
    scrollToBottomFAB: {
        position: 'absolute',
        bottom: 100,
        right: 16,
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: 'rgba(59, 130, 246, 0.9)',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
    },
    replyingToContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 10,
        backgroundColor: '#F0F1F3',
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
    },
    replyingToContent: {
        flex: 1,
    },
    // Additional missing styles for IndividualChatScreen
    replyingToTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 2,
    },
    replyingToText: {
        fontSize: 13,
        color: '#6B7280',
    },
    replyingToCloseButton: {
        padding: 6,
        borderRadius: 12,
        backgroundColor: '#FFFFFF',
    },
    modalBackdrop: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    actionModalContent: {
        position: 'absolute',
        bottom: Platform.OS === 'ios' ? 34 : 20,
        left: 16,
        right: 16,
        backgroundColor: 'white',
        borderRadius: 16,
        paddingVertical: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 8,
    },
    actionModalButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 14,
        paddingHorizontal: 20,
    },
    actionModalIcon: {
        marginRight: 16,
    },
    actionModalButtonText: {
        fontSize: 16,
        color: '#1F2937',
        fontWeight: '500',
    },
    // Additional modal styles for IndividualChatScreen
    modalContent: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'white',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 24,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 12,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 16,
        color: '#1F2937',
    },
    modalInput: {
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 16,
        marginBottom: 16,
        backgroundColor: '#FFFFFF',
    },
    modalActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 12,
    },
    modalButton: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
    },
    modalButtonCancel: {
        backgroundColor: '#F3F4F6',
    },
    modalButtonTextCancel: {
        color: '#6B7280',
        fontSize: 16,
        fontWeight: '600',
    },
    modalButtonSave: {
        backgroundColor: APP_CONSTANTS?.COLORS?.PRIMARY || '#3B82F6',
    },
    modalButtonDisabled: {
        backgroundColor: '#E5E7EB',
        opacity: 0.5,
    },
    // Additional missing styles for IndividualChatScreen
    modalButtonTextSave: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
    messageInfoModalContent: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        maxHeight: '60%',
        backgroundColor: 'white',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 24,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 12,
    },
    messageInfoTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 16,
        color: '#1F2937',
    },
    messageInfoSectionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 8,
    },
    messageInfoDetailText: {
        fontSize: 14,
        color: '#6B7280',
        marginBottom: 4,
    },
    messageInfoCloseButton: {
        marginTop: 24,
        paddingVertical: 14,
        backgroundColor: APP_CONSTANTS?.COLORS?.PRIMARY || '#3B82F6',
        borderRadius: 12,
        alignItems: 'center',
    },
    messageInfoCloseButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '600',
    },
    forwardModalContent: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        maxHeight: '80%',
        backgroundColor: 'white',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 24,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 12,
    },
    forwardModalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 16,
        color: '#1F2937',
    },
    // Additional forward modal styles for IndividualChatScreen
    forwardMessagePreview: {
        backgroundColor: '#F3F4F6',
        padding: 12,
        borderRadius: 8,
        marginBottom: 16,
    },
    forwardMessagePreviewText: {
        fontSize: 14,
        color: '#4B5563',
        fontStyle: 'italic',
    },
    forwardModalSubtitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 12,
    },
    forwardLoadingContainer: {
        alignItems: 'center',
        paddingVertical: 40,
    },
    forwardLoadingText: {
        marginTop: 12,
        fontSize: 14,
        color: '#6B7280',
    },
    forwardEmptyContainer: {
        alignItems: 'center',
        paddingVertical: 40,
    },
    forwardEmptyText: {
        fontSize: 14,
        color: '#6B7280',
        fontStyle: 'italic',
    },
    forwardChatsList: {
        maxHeight: 300,
    },
    // Additional forward chat styles for IndividualChatScreen
    forwardChatItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 16,
        paddingHorizontal: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
    },
    forwardChatInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    forwardChatIcon: {
        marginRight: 12,
    },
    forwardChatName: {
        fontSize: 16,
        color: '#1F2937',
        fontWeight: '500',
    },
    forwardModalCloseButton: {
        marginTop: 24,
        paddingVertical: 14,
        backgroundColor: '#F3F4F6',
        borderRadius: 12,
        alignItems: 'center',
    },
    forwardModalCloseButtonText: {
        color: '#4B5563',
        fontSize: 16,
        fontWeight: '600',
    },
    // Enhanced modern styles for better UX
    messageStatusContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 2,
    },
    messageStatusIcon: {
        marginLeft: 4,
    },
    messageStatusText: {
        fontSize: 10,
        color: 'rgba(255, 255, 255, 0.7)',
        marginLeft: 2,
    },
    messageReactionsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 4,
        flexWrap: 'wrap',
    },
    reactionButton: {
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        borderRadius: 12,
        paddingHorizontal: 8,
        paddingVertical: 4,
        marginRight: 4,
        marginBottom: 2,
        borderWidth: 1,
        borderColor: 'rgba(0, 0, 0, 0.1)',
    },
    reactionText: {
        fontSize: 12,
        color: '#374151',
        fontWeight: '500',
    },
    messageTimestamp: {
        fontSize: 10,
        color: 'rgba(255, 255, 255, 0.6)',
        marginTop: 2,
        alignSelf: 'flex-end',
    },
    messageTimestampReceived: {
        color: '#9CA3AF',
    },
    // Enhanced input styles
    inputContainer: {
        backgroundColor: APP_CONSTANTS?.COLORS?.WHITE || '#FFFFFF',
        borderTopWidth: 1,
        borderTopColor: APP_CONSTANTS?.COLORS?.BORDER_LIGHT || '#F3F4F6',
        paddingBottom: Platform.OS === 'ios' ? 20 : 0,
    },
    inputActionsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: Platform.OS === 'web' ? 20 : 16,
        paddingVertical: Platform.OS === 'web' ? 8 : 6,
    },
    actionButton: {
        padding: Platform.OS === 'web' ? 10 : 8,
        borderRadius: Platform.OS === 'web' ? 12 : 8,
        marginRight: Platform.OS === 'web' ? 12 : 8,
        backgroundColor: 'transparent',
    },
    actionButtonActive: {
        backgroundColor: APP_CONSTANTS?.COLORS?.PRIMARY_LIGHT || '#DBEAFE',
    },
    // Enhanced scroll indicator
    scrollIndicator: {
        position: 'absolute',
        bottom: Platform.OS === 'web' ? 120 : 100,
        right: Platform.OS === 'web' ? 20 : 16,
        backgroundColor: 'rgba(59, 130, 246, 0.9)',
        borderRadius: 20,
        paddingHorizontal: 12,
        paddingVertical: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 4,
    },
    scrollIndicatorText: {
        color: '#FFFFFF',
        fontSize: 12,
        fontWeight: '600',
    },
});

// GroupChatScreen Styles (similar to IndividualChatScreen but with group-specific additions)
export const groupChatScreenStyles = StyleSheet.create({
    // Include all the same styles as individualChatScreenStyles
    ...individualChatScreenStyles,
    // Add any group-specific styles here
    groupHeaderContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        flex: 1,
    },
    groupHeaderImage: {
        width: Platform.OS === 'web' ? 40 : 34,
        height: Platform.OS === 'web' ? 40 : 34,
        borderRadius: Platform.OS === 'web' ? 20 : 17,
        marginRight: Platform.OS === 'web' ? 12 : 10,
        borderWidth: 2,
        borderColor: APP_CONSTANTS?.COLORS?.BORDER_LIGHT || '#F3F4F6',
    },
    groupHeaderTitle: {
        fontSize: Platform.OS === 'web' ? 18 : 17,
        fontWeight: '600',
        color: APP_CONSTANTS?.COLORS?.TEXT_PRIMARY || '#1F2937',
        marginBottom: Platform.OS === 'web' ? 2 : 1,
    },
    groupMemberCount: {
        fontSize: Platform.OS === 'web' ? 13 : 12,
        color: APP_CONSTANTS?.COLORS?.TEXT_SECONDARY || '#6B7280',
        marginTop: Platform.OS === 'web' ? 2 : 1,
    },
    // Additional group-specific styles that were missing
    systemMessageContainer: {
        alignSelf: 'center',
        backgroundColor: 'rgba(107, 114, 128, 0.08)',
        borderRadius: Platform.OS === 'web' ? 16 : 12,
        paddingHorizontal: Platform.OS === 'web' ? 16 : 12,
        paddingVertical: Platform.OS === 'web' ? 8 : 6,
        marginVertical: Platform.OS === 'web' ? 12 : 8,
        maxWidth: '80%',
        borderWidth: 1,
        borderColor: 'rgba(107, 114, 128, 0.1)',
    },
    systemMessageText: {
        fontSize: Platform.OS === 'web' ? 13 : 12,
        color: APP_CONSTANTS?.COLORS?.TEXT_SECONDARY || '#4B5563',
        textAlign: 'center',
        fontStyle: 'italic',
        fontWeight: '500',
    },
    senderInfoContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: Platform.OS === 'web' ? 6 : 4,
    },
    senderAvatar: {
        width: Platform.OS === 'web' ? 36 : 32,
        height: Platform.OS === 'web' ? 36 : 32,
        borderRadius: Platform.OS === 'web' ? 18 : 16,
        marginRight: Platform.OS === 'web' ? 10 : 8,
        borderWidth: 1,
        borderColor: APP_CONSTANTS?.COLORS?.BORDER_LIGHT || '#F3F4F6',
    },
    senderName: {
        fontSize: Platform.OS === 'web' ? 13 : 12,
        color: APP_CONSTANTS?.COLORS?.TEXT_SECONDARY || '#6B7280',
        marginBottom: Platform.OS === 'web' ? 6 : 4,
        marginLeft: Platform.OS === 'web' ? 8 : 6,
        alignSelf: 'flex-start',
        fontWeight: '500',
    },
    deletedMessageBubble: {
        paddingVertical: 10,
        paddingHorizontal: 14,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F3F4F6',
        opacity: 0.8,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    deletedMessageText: {
        fontSize: 14,
        fontStyle: 'italic',
        color: '#6B7280',
    },
    messageRowTouchable: {
        flexDirection: 'row',
        marginVertical: 4,
        alignItems: 'flex-end',
    },
    highlightedMessageContainer: {
        backgroundColor: 'rgba(59, 130, 246, 0.1)',
        borderRadius: 12,
        padding: 4,
        margin: 2,
    },
    highlightedMessageBubble: {
        borderWidth: 2,
        borderColor: 'rgba(59, 130, 246, 0.3)',
        shadowColor: '#3B82F6',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 4,
    },
    highlightedImageBubble: {
        borderWidth: 2,
        borderColor: 'rgba(59, 130, 246, 0.3)',
        shadowColor: '#3B82F6',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 4,
    },
    sharedEventMessageBubble: {
        padding: 14,
        maxWidth: 300,
    },
    sharedEventPreview: {
        marginTop: 10,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.08)',
        overflow: 'hidden',
        backgroundColor: '#FFFFFF',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    sharedEventPreviewImage: {
        width: '100%',
        height: 140,
        backgroundColor: '#F3F4F6',
    },
    sharedEventPreviewContent: {
        padding: 12,
    },
    sharedEventPreviewTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 4,
    },
    sharedEventPreviewDetails: {
        fontSize: 13,
        color: '#6B7280',
        marginBottom: 2,
    },
    sharedEventPreviewDisabled: {
        opacity: 0.5,
    },
    sharedEventPreviewImageDisabled: {
        backgroundColor: '#F3F4F6',
    },
    eventOverOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.4)',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 16,
    },
    eventOverText: {
        color: '#FFFFFF',
        fontSize: 12,
        marginTop: 4,
        textAlign: 'center',
    },
    eventOverTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 2,
    },
    eventOverDetails: {
        fontSize: 13,
        color: '#6B7280',
        marginBottom: 1,
    },
    messageInfoDetailText: {
        fontSize: 14,
        color: '#6B7280',
        marginTop: 4,
    },
    headerTextContainer: {
        flex: 1,
        alignItems: 'center',
    },
    typingIndicatorContainer: {
        paddingHorizontal: 15,
        paddingBottom: 5,
        height: 25,
        backgroundColor: '#F9FAFB',
    },
    typingIndicatorText: {
        fontSize: 12,
        color: '#6B7280',
        fontStyle: 'italic',
    },
    headerImageContainer: {
        position: 'relative',
        marginRight: 10,
    },
    onlineIndicator: {
        position: 'absolute',
        bottom: -2,
        right: -2,
        width: 16,
        height: 16,
        borderRadius: 8,
        backgroundColor: '#22C55E',
        borderWidth: 2,
        borderColor: '#FFFFFF',
        justifyContent: 'center',
        alignItems: 'center',
    },
    onlineIndicatorText: {
        color: '#FFFFFF',
        fontSize: 10,
        fontWeight: 'bold',
    },
    headerSubtitleText: {
        fontSize: 11,
        color: '#6B7280',
        marginTop: 2,
    },
    newMessagesDivider: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 8,
        marginBottom: 4,
    },
    newMessagesDividerLine: {
        flex: 1,
        height: 1,
        backgroundColor: APP_CONSTANTS?.COLORS?.PRIMARY || '#3B82F6',
        opacity: 0.6,
    },
    newMessagesDividerText: {
        fontSize: 12,
        fontWeight: '600',
        color: APP_CONSTANTS?.COLORS?.PRIMARY || '#3B82F6',
        marginHorizontal: 8,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    scrollToBottomFAB: {
        position: 'absolute',
        bottom: 100,
        right: 20,
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: APP_CONSTANTS?.COLORS?.PRIMARY || '#3B82F6',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
        zIndex: 1000,
    },
    headerButtons: {
        flexDirection: 'row',
        marginRight: Platform.OS === 'ios' ? 5 : 10,
    },
    headerButton: {
        paddingHorizontal: 8,
        paddingVertical: 6,
    },
    headerGroupImage: {
        width: 34,
        height: 34,
        borderRadius: 17,
        marginRight: 10,
        backgroundColor: '#E5E7EB',
    },
    headerTitleText: {
        fontSize: Platform.OS === 'web' ? 18 : 17,
        fontWeight: '600',
        color: APP_CONSTANTS?.COLORS?.TEXT_PRIMARY || '#1F2937',
        marginBottom: Platform.OS === 'web' ? 2 : 1,
    },
    headerTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        flex: 1,
    },
    headerInfoButton: {
        padding: 5,
    },
    onlineCount: {
        fontSize: 10,
        color: 'white',
        fontWeight: '600',
    },
    centeredEmptyList: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: 50,
        minHeight: 200,
    },
    errorBanner: {
        backgroundColor: 'rgba(239, 68, 68, 0.1)',
        paddingVertical: 8,
        paddingHorizontal: 15,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(239, 68, 68, 0.2)',
    },
    errorBannerText: {
        color: '#B91C1C',
        fontSize: 13,
        flexShrink: 1,
        marginRight: 10,
    },
    errorBannerClose: {
        padding: 4,
    },
    messageBubbleSentText: {
        backgroundColor: APP_CONSTANTS?.COLORS?.PRIMARY || '#3B82F6',
        borderBottomRightRadius: 4,
        alignSelf: 'flex-end',
        paddingVertical: 10,
        paddingHorizontal: 14,
    },
    messageBubbleReceivedText: {
        backgroundColor: '#FFFFFF',
        borderBottomLeftRadius: 4,
        alignSelf: 'flex-start',
        paddingVertical: 10,
        paddingHorizontal: 14,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    seenByText: {
        alignSelf: 'flex-end',
        fontSize: 11,
        color: '#9CA3AF',
        marginRight: 8,
        marginTop: 2,
    },
    inputToolbar: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
        backgroundColor: '#FFFFFF',
        paddingBottom: Platform.OS === 'ios' ? 8 : 12,
    },
    attachButton: {
        width: 44,
        height: 44,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 22,
        backgroundColor: '#F8F9FA',
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    textInput: {
        flex: 1,
        minHeight: 44,
        maxHeight: 120,
        backgroundColor: '#F8F9FA',
        borderRadius: 22,
        paddingHorizontal: 16,
        paddingVertical: Platform.OS === 'ios' ? 12 : 10,
        fontSize: 16,
        marginHorizontal: 8,
        color: '#1F2937',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        textAlignVertical: 'center',
    },
    sendButton: {
        backgroundColor: APP_CONSTANTS?.COLORS?.PRIMARY || '#3B82F6',
        width: 44,
        height: 44,
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: Platform.OS === 'ios' ? 0 : 1,
    },
    sendButtonDisabled: {
        backgroundColor: '#9CA3AF',
    },
    modalBackdrop: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        position: 'absolute',
        top: '25%',
        left: '8%',
        right: '8%',
        backgroundColor: 'white',
        borderRadius: 16,
        padding: 28,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
        width: '84%',
        minHeight: 220,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: '600',
        marginBottom: 24,
        textAlign: 'center',
        color: '#1F2937',
    },
    modalInput: {
        borderWidth: 1,
        borderColor: '#D1D5DB',
        borderRadius: 10,
        paddingHorizontal: 16,
        paddingVertical: 14,
        fontSize: 16,
        marginBottom: 28,
    },
    modalActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    modalButton: {
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        minWidth: 100,
    },
    modalButtonCancel: {
        backgroundColor: '#F3F4F6',
    },
    modalButtonSave: {
        backgroundColor: APP_CONSTANTS?.COLORS?.PRIMARY || '#3B82F6',
    },
    modalButtonDisabled: {
        backgroundColor: '#D1D5DB',
    },
    modalButtonTextCancel: {
        color: '#4B5563',
        fontWeight: '600',
    },
    modalButtonTextSave: {
        color: 'white',
        fontWeight: '600',
    },
    imageViewerContainer: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.9)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    imageViewerCloseButton: {
        position: 'absolute',
        top: Platform.OS === 'ios' ? 50 : 20,
        right: 20,
        zIndex: 1,
        padding: 10,
    },
    fullScreenImage: {
        width: '100%',
        height: '100%',
    },
    imageViewerControls: {
        position: 'absolute',
        bottom: 40,
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        paddingHorizontal: 20,
    },
    imageViewerButton: {
        padding: 10,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        borderRadius: 25,
    },
    imageViewerButtonDisabled: {
        opacity: 0.5,
    },
    sharedEventContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
        backgroundColor: '#F8F9FA',
    },
    sharedEventContent: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    sharedEventImage: {
        width: 50,
        height: 50,
        borderRadius: 10,
        marginRight: 12,
    },
    sharedEventInfo: {
        flex: 1,
    },
    sharedEventTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 2,
    },
    sharedEventDetails: {
        fontSize: 13,
        color: '#6B7280',
        marginBottom: 1,
    },
    sharedEventCloseButton: {
        padding: 8,
        borderRadius: 16,
        backgroundColor: '#FFFFFF',
    },
    loadingOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
    },
    loadingOverlayText: {
        marginTop: 12,
        color: 'white',
        fontSize: 16,
    },
    editedIndicator: {
        fontSize: 10,
        fontStyle: 'italic',
        marginRight: 6,
    },
    editedIndicatorSent: {
        color: 'rgba(255, 255, 255, 0.7)',
    },
    editedIndicatorReceived: {
        color: '#6B7280',
    },
    editedIndicatorImage: {
        position: 'absolute',
        bottom: 8,
        right: 8,
        backgroundColor: 'rgba(0,0,0,0.6)',
        color: 'white',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 4,
        fontSize: 9,
    },
    replyPreviewContainer: {
        flexDirection: 'row',
        backgroundColor: 'rgba(0,0,0,0.04)',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderTopLeftRadius: 12,
        borderTopRightRadius: 12,
        marginBottom: -2,
        maxWidth: '90%',
    },
    replyPreviewSent: {
        alignSelf: 'flex-end',
        borderLeftColor: APP_CONSTANTS?.COLORS?.PRIMARY || '#3B82F6',
        borderLeftWidth: 3,
    },
    replyPreviewReceived: {
        alignSelf: 'flex-start',
        borderLeftColor: '#A0AEC0',
        borderLeftWidth: 3,
    },
    replyPreviewBorder: {
    },
    replyPreviewContent: {
        marginLeft: 8,
        flexShrink: 1,
    },
    replyPreviewSenderName: {
        fontSize: 12,
        fontWeight: '600',
        color: '#4B5563',
        marginBottom: 2,
    },
    replyPreviewText: {
        fontSize: 12,
        color: '#6B7280',
    },
    replyingToContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 10,
        backgroundColor: '#F0F1F3',
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
    },
    replyingToContent: {
        flex: 1,
    },
    replyingToTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 2,
    },
    replyingToText: {
        fontSize: 13,
        color: '#6B7280',
    },
    replyingToCloseButton: {
        padding: 6,
        borderRadius: 12,
        backgroundColor: '#FFFFFF',
    },
    actionModalContent: {
        position: 'absolute',
        bottom: Platform.OS === 'ios' ? 34 : 20,
        left: 16,
        right: 16,
        backgroundColor: 'white',
        borderRadius: 16,
        paddingVertical: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 8,
    },
    actionModalButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 14,
        paddingHorizontal: 20,
    },
    actionModalIcon: {
        marginRight: 16,
    },
    actionModalButtonText: {
        fontSize: 16,
        color: '#1F2937',
        fontWeight: '500',
    },
    messageInfoModalContent: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        maxHeight: '60%',
        backgroundColor: 'white',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 24,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 12,
    },
    messageInfoTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 20,
        color: '#1F2937',
    },
    messageInfoSectionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#374151',
        marginTop: 12,
        marginBottom: 8,
    },
    messageInfoMemberRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
    },
    messageInfoMemberImage: {
        width: 36,
        height: 36,
        borderRadius: 18,
        marginRight: 12,
    },
    messageInfoMemberInfo: {
        flex: 1,
    },
    messageInfoMemberName: {
        fontSize: 15,
        fontWeight: '500',
        color: '#1F2937',
        marginBottom: 2,
    },
    messageInfoStatusText: {
        fontSize: 13,
        color: '#6B7280',
        marginTop: 2,
    },
    messageInfoCloseButton: {
        marginTop: 24,
        paddingVertical: 14,
        backgroundColor: APP_CONSTANTS?.COLORS?.PRIMARY || '#3B82F6',
        borderRadius: 12,
        alignItems: 'center',
    },
    messageInfoCloseButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '600',
    },
    forwardModalContent: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        maxHeight: '80%',
        backgroundColor: 'white',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 24,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 12,
    },
    forwardModalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 16,
        color: '#1F2937',
    },
    forwardMessagePreview: {
        backgroundColor: '#F3F4F6',
        padding: 12,
        borderRadius: 8,
        marginBottom: 16,
    },
    forwardMessagePreviewText: {
        fontSize: 14,
        color: '#4B5563',
        fontStyle: 'italic',
    },
    forwardModalSubtitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 12,
    },
    forwardLoadingContainer: {
        alignItems: 'center',
        paddingVertical: 40,
    },
    forwardLoadingText: {
        marginTop: 12,
        fontSize: 14,
        color: '#6B7280',
    },
    forwardEmptyContainer: {
        alignItems: 'center',
        paddingVertical: 40,
    },
    forwardEmptyText: {
        fontSize: 14,
        color: '#6B7280',
        fontStyle: 'italic',
    },
    forwardChatsList: {
        maxHeight: 300,
    },
    forwardChatItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 16,
        paddingHorizontal: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
    },
    forwardChatInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    forwardChatIcon: {
        marginRight: 12,
    },
    forwardChatName: {
        fontSize: 16,
        color: '#1F2937',
        fontWeight: '500',
    },
    forwardModalCloseButton: {
        marginTop: 24,
        paddingVertical: 14,
        backgroundColor: '#F3F4F6',
        borderRadius: 12,
        alignItems: 'center',
    },
    forwardModalCloseButtonText: {
        color: '#4B5563',
        fontSize: 16,
        fontWeight: '600',
    },
});
